apiVersion: v1
kind: Service
metadata:
  name: soundxbackendservice
spec:
  selector:
    app: soundxbackendlabel
  type: LoadBalancer
  ports:
    - name: soundxbackendport
      port: 80
      targetPort: 8000
  externalIPs:
    - 192.168.64.2