apiVersion: v1
kind: Service
metadata:
  name: soundxdatabaseservice
  labels:
    name: soundxdatabasestatefulset
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    role: soundxmongolabel