apiVersion: v1
kind: Service
metadata:
  name: soundxfrontendservice
spec:
  selector:
    app: soundxfrontendlabel
  type: LoadBalancer
  ports:
    - name: soundxfrontendport
      port: 5000
      targetPort: 5000
  externalIPs:
    - 192.168.64.2