apiVersion: apps/v1
kind: Deployment
metadata:
  name: soundxfrontenddeployment
spec:
  selector:
    matchLabels:
      app: soundxfrontendlabel
  replicas: 1
  template:
    metadata:
      labels:
        app: soundxfrontendlabel
    spec:
      containers:
        - name: soundxfrontend
          imagePullPolicy: Never
          image: soundx-frontend
          ports:
            - containerPort: 5000